# Generated by Django 5.1.1 on 2024-11-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
