# Generated by Django 5.1.1 on 2024-10-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
