# Generated by Django 5.1.1 on 2024-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(default='farmer', max_length=10),
        ),
    ]
