# Generated by Django 5.1.1 on 2024-10-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_farmer'),
    ]

    operations = [
    ]
